/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BasicNft__factory } from "./BasicNft__factory";
export { MockERC20__factory } from "./MockERC20__factory";
