/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBasicNft } from "./IBasicNft";
export type { IERC2981 } from "./IERC2981";
export type { IFundABusiness } from "./IFundABusiness";
export type { IMockERC1155 } from "./IMockERC1155";
export type { INftCommon } from "./INftCommon";
