/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace IFundABusiness {
  export type FundingTierCostStruct = {
    fundingTier: PromiseOrValue<BigNumberish>;
    tierCost: PromiseOrValue<BigNumberish>;
  };

  export type FundingTierCostStructOutput = [BigNumber, BigNumber] & {
    fundingTier: BigNumber;
    tierCost: BigNumber;
  };

  export type MilestoneCheckpointStruct = {
    milestonePeriod: PromiseOrValue<BigNumberish>;
    cumFractionToBeReleased: PromiseOrValue<BigNumberish>;
  };

  export type MilestoneCheckpointStructOutput = [BigNumber, BigNumber] & {
    milestonePeriod: BigNumber;
    cumFractionToBeReleased: BigNumber;
  };

  export type NftTierContractStruct = {
    fundingTier: PromiseOrValue<BigNumberish>;
    nftContract: PromiseOrValue<string>;
  };

  export type NftTierContractStructOutput = [BigNumber, string] & {
    fundingTier: BigNumber;
    nftContract: string;
  };
}

export interface FundABusinessInterface extends utils.Interface {
  functions: {
    "DEFAULT_ADMIN_ROLE()": FunctionFragment;
    "MANAGER_ROLE()": FunctionFragment;
    "PAUSER_ROLE()": FunctionFragment;
    "allowedErc20Token()": FunctionFragment;
    "businessAddress()": FunctionFragment;
    "campaignEndTime()": FunctionFragment;
    "campaignStartTime()": FunctionFragment;
    "cancelFundingRound()": FunctionFragment;
    "claimNft()": FunctionFragment;
    "claimNftFor(address)": FunctionFragment;
    "claimRefund()": FunctionFragment;
    "claimRefundFor(address)": FunctionFragment;
    "contribute(uint256)": FunctionFragment;
    "contributeOnBehalfOf(address[],uint256[],uint256)": FunctionFragment;
    "cumFundReleased()": FunctionFragment;
    "fundRaised()": FunctionFragment;
    "funderTier(address)": FunctionFragment;
    "getFundersAddresses()": FunctionFragment;
    "getRoleAdmin(bytes32)": FunctionFragment;
    "grantRole(bytes32,address)": FunctionFragment;
    "hasClaimedNft(address)": FunctionFragment;
    "hasRole(bytes32,address)": FunctionFragment;
    "isCampaignSuccessful()": FunctionFragment;
    "minTargetAmount()": FunctionFragment;
    "nftTierContract(uint256)": FunctionFragment;
    "pause()": FunctionFragment;
    "paused()": FunctionFragment;
    "renounceRole(bytes32,address)": FunctionFragment;
    "revokeRole(bytes32,address)": FunctionFragment;
    "setAllowedToken(address)": FunctionFragment;
    "setBusinessAddress(address)": FunctionFragment;
    "setCampaignPeriod(uint256[])": FunctionFragment;
    "setFundingTiersAndCosts((uint256,uint256)[])": FunctionFragment;
    "setMilestonesSchedule((uint256,uint256)[])": FunctionFragment;
    "setNftContracts((uint256,address)[])": FunctionFragment;
    "setTargetAmounts(uint256[])": FunctionFragment;
    "setTreasuryAddress(address)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "targetAmount()": FunctionFragment;
    "tierCost(uint256)": FunctionFragment;
    "unpause()": FunctionFragment;
    "withdrawFundRaised()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "DEFAULT_ADMIN_ROLE"
      | "MANAGER_ROLE"
      | "PAUSER_ROLE"
      | "allowedErc20Token"
      | "businessAddress"
      | "campaignEndTime"
      | "campaignStartTime"
      | "cancelFundingRound"
      | "claimNft"
      | "claimNftFor"
      | "claimRefund"
      | "claimRefundFor"
      | "contribute"
      | "contributeOnBehalfOf"
      | "cumFundReleased"
      | "fundRaised"
      | "funderTier"
      | "getFundersAddresses"
      | "getRoleAdmin"
      | "grantRole"
      | "hasClaimedNft"
      | "hasRole"
      | "isCampaignSuccessful"
      | "minTargetAmount"
      | "nftTierContract"
      | "pause"
      | "paused"
      | "renounceRole"
      | "revokeRole"
      | "setAllowedToken"
      | "setBusinessAddress"
      | "setCampaignPeriod"
      | "setFundingTiersAndCosts"
      | "setMilestonesSchedule"
      | "setNftContracts"
      | "setTargetAmounts"
      | "setTreasuryAddress"
      | "supportsInterface"
      | "targetAmount"
      | "tierCost"
      | "unpause"
      | "withdrawFundRaised"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MANAGER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PAUSER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allowedErc20Token",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "businessAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "campaignEndTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "campaignStartTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelFundingRound",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "claimNft", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "claimNftFor",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRefund",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimRefundFor",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "contribute",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "contributeOnBehalfOf",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "cumFundReleased",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fundRaised",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "funderTier",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getFundersAddresses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "hasClaimedNft",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isCampaignSuccessful",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minTargetAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nftTierContract",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setAllowedToken",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setBusinessAddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setCampaignPeriod",
    values: [PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setFundingTiersAndCosts",
    values: [IFundABusiness.FundingTierCostStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setMilestonesSchedule",
    values: [IFundABusiness.MilestoneCheckpointStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setNftContracts",
    values: [IFundABusiness.NftTierContractStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setTargetAmounts",
    values: [PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasuryAddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "targetAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tierCost",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawFundRaised",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MANAGER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PAUSER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allowedErc20Token",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "businessAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "campaignEndTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "campaignStartTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelFundingRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimNft", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimNftFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRefundFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "contribute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "contributeOnBehalfOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cumFundReleased",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fundRaised", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "funderTier", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getFundersAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasClaimedNft",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isCampaignSuccessful",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minTargetAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nftTierContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAllowedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBusinessAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCampaignPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFundingTiersAndCosts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMilestonesSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setNftContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTargetAmounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasuryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "targetAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tierCost", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFundRaised",
    data: BytesLike
  ): Result;

  events: {
    "ContributionReceived(address,uint256)": EventFragment;
    "ContributionRefunded(address,uint256)": EventFragment;
    "FiatContributionReceived(address,uint256)": EventFragment;
    "FundReleased(address,uint256,uint256)": EventFragment;
    "NFTRewardClaimed(address,uint256)": EventFragment;
    "Paused(address)": EventFragment;
    "RoleAdminChanged(bytes32,bytes32,bytes32)": EventFragment;
    "RoleGranted(bytes32,address,address)": EventFragment;
    "RoleRevoked(bytes32,address,address)": EventFragment;
    "Unpaused(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ContributionReceived"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ContributionRefunded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FiatContributionReceived"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FundReleased"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NFTRewardClaimed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleAdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleRevoked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
}

export interface ContributionReceivedEventObject {
  funder: string;
  tier: BigNumber;
}
export type ContributionReceivedEvent = TypedEvent<
  [string, BigNumber],
  ContributionReceivedEventObject
>;

export type ContributionReceivedEventFilter =
  TypedEventFilter<ContributionReceivedEvent>;

export interface ContributionRefundedEventObject {
  funder: string;
  tier: BigNumber;
}
export type ContributionRefundedEvent = TypedEvent<
  [string, BigNumber],
  ContributionRefundedEventObject
>;

export type ContributionRefundedEventFilter =
  TypedEventFilter<ContributionRefundedEvent>;

export interface FiatContributionReceivedEventObject {
  funder: string;
  amount: BigNumber;
}
export type FiatContributionReceivedEvent = TypedEvent<
  [string, BigNumber],
  FiatContributionReceivedEventObject
>;

export type FiatContributionReceivedEventFilter =
  TypedEventFilter<FiatContributionReceivedEvent>;

export interface FundReleasedEventObject {
  business: string;
  amount: BigNumber;
  time: BigNumber;
}
export type FundReleasedEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  FundReleasedEventObject
>;

export type FundReleasedEventFilter = TypedEventFilter<FundReleasedEvent>;

export interface NFTRewardClaimedEventObject {
  funder: string;
  tier: BigNumber;
}
export type NFTRewardClaimedEvent = TypedEvent<
  [string, BigNumber],
  NFTRewardClaimedEventObject
>;

export type NFTRewardClaimedEventFilter =
  TypedEventFilter<NFTRewardClaimedEvent>;

export interface PausedEventObject {
  account: string;
}
export type PausedEvent = TypedEvent<[string], PausedEventObject>;

export type PausedEventFilter = TypedEventFilter<PausedEvent>;

export interface RoleAdminChangedEventObject {
  role: string;
  previousAdminRole: string;
  newAdminRole: string;
}
export type RoleAdminChangedEvent = TypedEvent<
  [string, string, string],
  RoleAdminChangedEventObject
>;

export type RoleAdminChangedEventFilter =
  TypedEventFilter<RoleAdminChangedEvent>;

export interface RoleGrantedEventObject {
  role: string;
  account: string;
  sender: string;
}
export type RoleGrantedEvent = TypedEvent<
  [string, string, string],
  RoleGrantedEventObject
>;

export type RoleGrantedEventFilter = TypedEventFilter<RoleGrantedEvent>;

export interface RoleRevokedEventObject {
  role: string;
  account: string;
  sender: string;
}
export type RoleRevokedEvent = TypedEvent<
  [string, string, string],
  RoleRevokedEventObject
>;

export type RoleRevokedEventFilter = TypedEventFilter<RoleRevokedEvent>;

export interface UnpausedEventObject {
  account: string;
}
export type UnpausedEvent = TypedEvent<[string], UnpausedEventObject>;

export type UnpausedEventFilter = TypedEventFilter<UnpausedEvent>;

export interface FundABusiness extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: FundABusinessInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    MANAGER_ROLE(overrides?: CallOverrides): Promise<[string]>;

    PAUSER_ROLE(overrides?: CallOverrides): Promise<[string]>;

    allowedErc20Token(overrides?: CallOverrides): Promise<[string]>;

    businessAddress(overrides?: CallOverrides): Promise<[string]>;

    campaignEndTime(overrides?: CallOverrides): Promise<[BigNumber]>;

    campaignStartTime(overrides?: CallOverrides): Promise<[BigNumber]>;

    cancelFundingRound(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    claimNft(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    claimNftFor(
      _funder: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    claimRefund(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    claimRefundFor(
      _funder: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    contribute(
      _tier: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    contributeOnBehalfOf(
      _funders: PromiseOrValue<string>[],
      _tiers: PromiseOrValue<BigNumberish>[],
      _totalAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    cumFundReleased(overrides?: CallOverrides): Promise<[BigNumber]>;

    fundRaised(overrides?: CallOverrides): Promise<[BigNumber]>;

    funderTier(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getFundersAddresses(overrides?: CallOverrides): Promise<[string[]]>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    hasClaimedNft(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isCampaignSuccessful(overrides?: CallOverrides): Promise<[boolean]>;

    minTargetAmount(overrides?: CallOverrides): Promise<[BigNumber]>;

    nftTierContract(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setAllowedToken(
      _allowedErc20Token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setBusinessAddress(
      _businessAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setCampaignPeriod(
      _campaignTimes: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setFundingTiersAndCosts(
      _fundingTiers: IFundABusiness.FundingTierCostStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setMilestonesSchedule(
      _milestoneSchedule: IFundABusiness.MilestoneCheckpointStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setNftContracts(
      _nftTiersContracts: IFundABusiness.NftTierContractStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setTargetAmounts(
      _amountsToBeRaised: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setTreasuryAddress(
      _treasuryAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    targetAmount(overrides?: CallOverrides): Promise<[BigNumber]>;

    tierCost(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawFundRaised(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  MANAGER_ROLE(overrides?: CallOverrides): Promise<string>;

  PAUSER_ROLE(overrides?: CallOverrides): Promise<string>;

  allowedErc20Token(overrides?: CallOverrides): Promise<string>;

  businessAddress(overrides?: CallOverrides): Promise<string>;

  campaignEndTime(overrides?: CallOverrides): Promise<BigNumber>;

  campaignStartTime(overrides?: CallOverrides): Promise<BigNumber>;

  cancelFundingRound(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  claimNft(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  claimNftFor(
    _funder: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  claimRefund(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  claimRefundFor(
    _funder: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  contribute(
    _tier: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  contributeOnBehalfOf(
    _funders: PromiseOrValue<string>[],
    _tiers: PromiseOrValue<BigNumberish>[],
    _totalAmount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  cumFundReleased(overrides?: CallOverrides): Promise<BigNumber>;

  fundRaised(overrides?: CallOverrides): Promise<BigNumber>;

  funderTier(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getFundersAddresses(overrides?: CallOverrides): Promise<string[]>;

  getRoleAdmin(
    role: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  grantRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  hasClaimedNft(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  hasRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isCampaignSuccessful(overrides?: CallOverrides): Promise<boolean>;

  minTargetAmount(overrides?: CallOverrides): Promise<BigNumber>;

  nftTierContract(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  pause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  renounceRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  revokeRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setAllowedToken(
    _allowedErc20Token: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setBusinessAddress(
    _businessAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setCampaignPeriod(
    _campaignTimes: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setFundingTiersAndCosts(
    _fundingTiers: IFundABusiness.FundingTierCostStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setMilestonesSchedule(
    _milestoneSchedule: IFundABusiness.MilestoneCheckpointStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setNftContracts(
    _nftTiersContracts: IFundABusiness.NftTierContractStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setTargetAmounts(
    _amountsToBeRaised: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setTreasuryAddress(
    _treasuryAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  targetAmount(overrides?: CallOverrides): Promise<BigNumber>;

  tierCost(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  unpause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawFundRaised(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    MANAGER_ROLE(overrides?: CallOverrides): Promise<string>;

    PAUSER_ROLE(overrides?: CallOverrides): Promise<string>;

    allowedErc20Token(overrides?: CallOverrides): Promise<string>;

    businessAddress(overrides?: CallOverrides): Promise<string>;

    campaignEndTime(overrides?: CallOverrides): Promise<BigNumber>;

    campaignStartTime(overrides?: CallOverrides): Promise<BigNumber>;

    cancelFundingRound(overrides?: CallOverrides): Promise<void>;

    claimNft(overrides?: CallOverrides): Promise<void>;

    claimNftFor(
      _funder: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    claimRefund(overrides?: CallOverrides): Promise<void>;

    claimRefundFor(
      _funder: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    contribute(
      _tier: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    contributeOnBehalfOf(
      _funders: PromiseOrValue<string>[],
      _tiers: PromiseOrValue<BigNumberish>[],
      _totalAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    cumFundReleased(overrides?: CallOverrides): Promise<BigNumber>;

    fundRaised(overrides?: CallOverrides): Promise<BigNumber>;

    funderTier(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFundersAddresses(overrides?: CallOverrides): Promise<string[]>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    hasClaimedNft(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isCampaignSuccessful(overrides?: CallOverrides): Promise<boolean>;

    minTargetAmount(overrides?: CallOverrides): Promise<BigNumber>;

    nftTierContract(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    pause(overrides?: CallOverrides): Promise<void>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setAllowedToken(
      _allowedErc20Token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setBusinessAddress(
      _businessAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setCampaignPeriod(
      _campaignTimes: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    setFundingTiersAndCosts(
      _fundingTiers: IFundABusiness.FundingTierCostStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    setMilestonesSchedule(
      _milestoneSchedule: IFundABusiness.MilestoneCheckpointStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    setNftContracts(
      _nftTiersContracts: IFundABusiness.NftTierContractStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    setTargetAmounts(
      _amountsToBeRaised: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    setTreasuryAddress(
      _treasuryAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    targetAmount(overrides?: CallOverrides): Promise<BigNumber>;

    tierCost(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    unpause(overrides?: CallOverrides): Promise<void>;

    withdrawFundRaised(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "ContributionReceived(address,uint256)"(
      funder?: null,
      tier?: null
    ): ContributionReceivedEventFilter;
    ContributionReceived(
      funder?: null,
      tier?: null
    ): ContributionReceivedEventFilter;

    "ContributionRefunded(address,uint256)"(
      funder?: null,
      tier?: null
    ): ContributionRefundedEventFilter;
    ContributionRefunded(
      funder?: null,
      tier?: null
    ): ContributionRefundedEventFilter;

    "FiatContributionReceived(address,uint256)"(
      funder?: null,
      amount?: null
    ): FiatContributionReceivedEventFilter;
    FiatContributionReceived(
      funder?: null,
      amount?: null
    ): FiatContributionReceivedEventFilter;

    "FundReleased(address,uint256,uint256)"(
      business?: null,
      amount?: null,
      time?: null
    ): FundReleasedEventFilter;
    FundReleased(
      business?: null,
      amount?: null,
      time?: null
    ): FundReleasedEventFilter;

    "NFTRewardClaimed(address,uint256)"(
      funder?: null,
      tier?: null
    ): NFTRewardClaimedEventFilter;
    NFTRewardClaimed(funder?: null, tier?: null): NFTRewardClaimedEventFilter;

    "Paused(address)"(account?: null): PausedEventFilter;
    Paused(account?: null): PausedEventFilter;

    "RoleAdminChanged(bytes32,bytes32,bytes32)"(
      role?: PromiseOrValue<BytesLike> | null,
      previousAdminRole?: PromiseOrValue<BytesLike> | null,
      newAdminRole?: PromiseOrValue<BytesLike> | null
    ): RoleAdminChangedEventFilter;
    RoleAdminChanged(
      role?: PromiseOrValue<BytesLike> | null,
      previousAdminRole?: PromiseOrValue<BytesLike> | null,
      newAdminRole?: PromiseOrValue<BytesLike> | null
    ): RoleAdminChangedEventFilter;

    "RoleGranted(bytes32,address,address)"(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleGrantedEventFilter;
    RoleGranted(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleGrantedEventFilter;

    "RoleRevoked(bytes32,address,address)"(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleRevokedEventFilter;
    RoleRevoked(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleRevokedEventFilter;

    "Unpaused(address)"(account?: null): UnpausedEventFilter;
    Unpaused(account?: null): UnpausedEventFilter;
  };

  estimateGas: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    MANAGER_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    PAUSER_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    allowedErc20Token(overrides?: CallOverrides): Promise<BigNumber>;

    businessAddress(overrides?: CallOverrides): Promise<BigNumber>;

    campaignEndTime(overrides?: CallOverrides): Promise<BigNumber>;

    campaignStartTime(overrides?: CallOverrides): Promise<BigNumber>;

    cancelFundingRound(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    claimNft(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    claimNftFor(
      _funder: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    claimRefund(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    claimRefundFor(
      _funder: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    contribute(
      _tier: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    contributeOnBehalfOf(
      _funders: PromiseOrValue<string>[],
      _tiers: PromiseOrValue<BigNumberish>[],
      _totalAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    cumFundReleased(overrides?: CallOverrides): Promise<BigNumber>;

    fundRaised(overrides?: CallOverrides): Promise<BigNumber>;

    funderTier(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFundersAddresses(overrides?: CallOverrides): Promise<BigNumber>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    hasClaimedNft(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isCampaignSuccessful(overrides?: CallOverrides): Promise<BigNumber>;

    minTargetAmount(overrides?: CallOverrides): Promise<BigNumber>;

    nftTierContract(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setAllowedToken(
      _allowedErc20Token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setBusinessAddress(
      _businessAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setCampaignPeriod(
      _campaignTimes: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setFundingTiersAndCosts(
      _fundingTiers: IFundABusiness.FundingTierCostStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setMilestonesSchedule(
      _milestoneSchedule: IFundABusiness.MilestoneCheckpointStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setNftContracts(
      _nftTiersContracts: IFundABusiness.NftTierContractStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setTargetAmounts(
      _amountsToBeRaised: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setTreasuryAddress(
      _treasuryAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    targetAmount(overrides?: CallOverrides): Promise<BigNumber>;

    tierCost(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawFundRaised(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    DEFAULT_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    MANAGER_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    PAUSER_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    allowedErc20Token(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    businessAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    campaignEndTime(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    campaignStartTime(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    cancelFundingRound(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    claimNft(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    claimNftFor(
      _funder: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    claimRefund(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    claimRefundFor(
      _funder: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    contribute(
      _tier: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    contributeOnBehalfOf(
      _funders: PromiseOrValue<string>[],
      _tiers: PromiseOrValue<BigNumberish>[],
      _totalAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    cumFundReleased(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    fundRaised(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    funderTier(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFundersAddresses(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    hasClaimedNft(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isCampaignSuccessful(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    minTargetAmount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    nftTierContract(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setAllowedToken(
      _allowedErc20Token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setBusinessAddress(
      _businessAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setCampaignPeriod(
      _campaignTimes: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setFundingTiersAndCosts(
      _fundingTiers: IFundABusiness.FundingTierCostStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setMilestonesSchedule(
      _milestoneSchedule: IFundABusiness.MilestoneCheckpointStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setNftContracts(
      _nftTiersContracts: IFundABusiness.NftTierContractStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setTargetAmounts(
      _amountsToBeRaised: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setTreasuryAddress(
      _treasuryAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    targetAmount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tierCost(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawFundRaised(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
